//
//  VideoDetailResponse.swift
//  SwiftTube
//
//  Created by Zabir Raihan on 21/06/2025.
//

import Foundation

struct VideoDetailResponse: Codable {
    // Basic video info
    let url: String
    let title: String
    let description: String?
    let views: Int?
    let duration: Double?
    let likes: Int?
    let dislikes: Int?
    let livestream: Bool?
    let isShort: Bool?
    
    // Upload info
    let uploaded: Double?
    let uploadDate: String?
    let uploadedDate: String?
    
    // Thumbnails
    let thumbnail: String?
    let thumbnailUrl: String?
    
    // Channel/Author info
    let uploaderName: String?
    let uploader: String?
    let uploaderUrl: String?
    let uploaderAvatar: String?
    let uploaderSubscriberCount: Int?
    let avatarUrl: String?
    let avatar: String?
    
    // Additional content
    let subtitles: [CaptionResponse]?
    let chapters: [ChapterResponse]?
    let relatedStreams: [Video]?
    
    // Video streams
    let videoStreams: [VideoStreamResponse]?
    let audioStreams: [AudioStreamResponse]?
    let hls: String?
    
    // Computed properties
    var videoId: String {
        extractVideoId(from: url)
    }
    
    var channelId: String {
        uploaderUrl?.components(separatedBy: "/").last ?? "unknown"
    }
    
    var authorName: String {
        uploaderName ?? uploader ?? ""
    }
    
    var thumbnailURL: String? {
        thumbnail ?? thumbnailUrl
    }
    
    var isLive: Bool {
        livestream ?? (duration == -1)
    }
    
    var isShortVideo: Bool {
        isShort ?? ((duration ?? 0) <= 61)
    }
    
    var publishedDateString: String {
        if let uploadedTimestamp = uploaded, uploadedTimestamp > 0 {
            let date = Date(timeIntervalSince1970: uploadedTimestamp / 1000)
            return date.relativeTime
        } else if let uploadedString = uploadedDate ?? uploadDate {
            return uploadedString
        }
        return ""
    }
    
    var publishedDate: Date? {
        if let uploadedTimestamp = uploaded, uploadedTimestamp > 0 {
            return Date(timeIntervalSince1970: uploadedTimestamp / 1000)
        } else if let dateString = uploadedDate ?? uploadDate {
            let formatter = ISO8601DateFormatter()
            formatter.formatOptions = [.withInternetDateTime]
            return formatter.date(from: dateString)
        }
        return nil
    }
    
//    func toVideo() -> Video? {
//        Video(
//            id: videoId,
//            title: title,
//            author: authorName,
//            duration: duration ?? 0,
//            published: publishedDateString,
//            views: views ?? 0,
//            thumbnailURL: thumbnailURL.flatMap { URL(string: $0) },
//            isLive: isLive,
//            isShort: isShortVideo,
//            publishedAt: publishedDate,
//            channelId: channelId,
//            channelSubscriberCount: uploaderSubscriberCount
//        )
//    }
    
    private func extractVideoId(from url: String) -> String {
        if url.contains("watch?v=") {
            let components = url.components(separatedBy: "watch?v=")
            if components.count > 1 {
                return String(components[1].prefix(11))
            }
        }
        return url
    }
}

struct ChapterResponse: Codable {
    let title: String?
    let image: String?
    let start: Double?
    
    func toChapter() -> Chapter? {
        guard let title = title, let start = start else { return nil }
        return Chapter(
            title: title,
            startTime: start,
            thumbnailURL: image.flatMap { URL(string: $0) }
        )
    }
}

struct CaptionResponse: Codable {
    let url: String?
    let mimeType: String?
    let name: String?
    let code: String?
    let autoGenerated: Bool?
    
    func toCaption() -> Caption? {
        guard let url = url, let name = name else { return nil }
        return Caption(
            url: URL(string: url),
            name: name,
            code: code,
            autoGenerated: autoGenerated ?? false
        )
    }
}

struct VideoStreamResponse: Codable {
    let url: String?
    let format: String?
    let quality: String?
    let mimeType: String?
    let codec: String?
    let audioTrackId: String?
    let audioTrackName: String?
    let videoOnly: Bool?
    let itag: Int?
    let bitrate: Int?
    let initStart: Int?
    let initEnd: Int?
    let indexStart: Int?
    let indexEnd: Int?
    let width: Int?
    let height: Int?
    let fps: Int?
}

struct AudioStreamResponse: Codable {
    let url: String?
    let format: String?
    let quality: String?
    let mimeType: String?
    let codec: String?
    let audioTrackId: String?
    let audioTrackName: String?
    let audioTrackType: String?
    let audioTrackLocale: String?
    let videoOnly: Bool?
    let itag: Int?
    let bitrate: Int?
    let initStart: Int?
    let initEnd: Int?
    let indexStart: Int?
    let indexEnd: Int?
    let loudness: Double?
}
