//
//  CaptionResponse.swift
//  SwiftTube
//
//  Created by Zabir Raihan on 21/06/2025.
//

import Foundation

struct CaptionResponse: Codable {
    let url: String?
    let mimeType: String?
    let name: String?
    let code: String?
    let autoGenerated: Bool?
}
